import base64

import httpx

from gitinspector.models import PullRequestRef, ReviewResult
from gitinspector.review_comments import build_inline_review_comments


class GitHubClient:
    def __init__(self, token: str, api_url: str = "https://api.github.com") -> None:
        self._client = httpx.AsyncClient(
            base_url=api_url,
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30,
        )

    async def close(self) -> None:
        await self._client.aclose()

    async def get_pull_request(self, pr: PullRequestRef) -> dict:
        response = await self._client.get(
            f"/repos/{pr.owner}/{pr.repo}/pulls/{pr.number}"
        )
        response.raise_for_status()
        return response.json()

    async def get_pull_request_diff(self, pr: PullRequestRef) -> str:
        response = await self._client.get(
            f"/repos/{pr.owner}/{pr.repo}/pulls/{pr.number}",
            headers={"Accept": "application/vnd.github.v3.diff"},
        )
        response.raise_for_status()
        return response.text

    async def get_file(self, owner: str, repo: str, path: str, ref: str) -> dict:
        response = await self._client.get(
            f"/repos/{owner}/{repo}/contents/{path}",
            params={"ref": ref},
        )
        response.raise_for_status()
        return response.json()

    async def get_file_text(self, owner: str, repo: str, path: str, ref: str) -> str:
        file_payload = await self.get_file(owner, repo, path, ref)
        if file_payload.get("encoding") != "base64":
            return ""
        raw = base64.b64decode(file_payload.get("content", ""))
        return raw.decode("utf-8", errors="replace")

    async def get_repository_tree(
        self,
        owner: str,
        repo: str,
        ref: str,
    ) -> list[dict]:
        response = await self._client.get(
            f"/repos/{owner}/{repo}/git/trees/{ref}",
            params={"recursive": "1"},
        )
        response.raise_for_status()
        return response.json().get("tree", [])

    async def post_summary(
        self,
        pr: PullRequestRef,
        result: ReviewResult,
        diff: str = "",
    ) -> dict:
        findings = "\n".join(
            f"- **{item.severity.upper()}** `{item.path}:{item.line or '?'}` "
            f"{item.title}: {item.explanation}"
            for item in result.findings[:10]
        )
        body = (
            "## GitInspector Review\n\n"
            f"**Quality score:** {result.quality_score}/100\n\n"
            f"{result.summary}\n\n"
            "### Findings\n"
            f"{findings or 'No actionable findings.'}\n\n"
            "_Generated by a fully local review model._"
        )
        comments = build_inline_review_comments(result.findings, diff) if diff else []
        response = await self._client.post(
            f"/repos/{pr.owner}/{pr.repo}/pulls/{pr.number}/reviews",
            json={"body": body, "event": "COMMENT", "comments": comments},
        )
        response.raise_for_status()
        return response.json()
